# Central theme definition – used by all applications

# The palette section defines the colour palette. Each colour consists of a primary and secondary shade. These two
# shades can be used by visual elements as they choose. For example, one visual element might use them for semantic
# purposes, such as to distinguish between active and inactive states. Meanwhile, another visual element might form
# them into a gradient.
[palette]

# The predominant colour
# Usage examples: window background
dominant = { primary = "333333aa", secondary = "595959aa" }

# A contrast to the dominant colour
# Usage examples: standard text, rendered on the domainant background to be easily readable
contrast = { primary = "ddddddff", secondary = "aaaaaaff" }

# A sequential collection of additional colours which comprise the palette, and provide accents to the visual style.
[palette.accents]
first = { primary = "33ccffee", secondary = "00ff99ee" }
second = { primary = "ff6b6bee", secondary = "ff6b6bee" }
third = { primary = "feca57ff", secondary = "feca57ff" }
