# Central theme definition – used by all applications

# The palette section defines the colour palette. Each colour consists of a primary and secondary shade. These two
# shades can be used by visual elements as they choose. For example, one visual element might use them for semantic
# purposes, such as to distinguish between active and inactive states. Meanwhile, another visual element might form
# them into a gradient.
[palette]

# The predominant colour
# Usage examples: window background
dominant = { primary = "333333", secondary = "595959" }

# A contrast to the dominant colour
# Usage examples: standard text, rendered on the domainant background to be easily readable
contrast = { primary = "dddddd", secondary = "aaaaaa" }

# A sequential collection of additional colours which comprise the palette, and provide accents to the visual style.
[palette.accents]
first = { primary = "33ccff", secondary = "224488" }
second = { primary = "00ff99", secondary = "00ff99" }
third = { primary = "feca57", secondary = "feca57" }
