[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

command = "tuigreet --cmd hyprland --remember --time --asterisks --window-padding 2 --container-padding 2 --theme 'border=cyan;text=white;prompt=gray;time=gray;action=gray;button=cyan;container=black;input=white'"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
